data <- read.csv("Cours1.csv", fileEncoding = "UTF-8")
head(data)
str(data)
tab  <- table (data$appétence.codage..1.fort.4.mauvais)
barplot(tab,col = heat.colors(5),border = NA,xlab = "Appétence,(1 oui - 4 non)")
tab <- table(data$passé)
barplot(tab,xlab = "passé")
tab <- table(data$présent)
barplot(tab,xlab = "présent")
barplot(tab, col = heat.colors(5), border = NA, legend=T)
etik <- names(tab)
barplot(tab,names.arg = etik,las=2)
